_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 49
                - 55
                - 83
            "2":
                - 1
                - 49
                - 55
                - 83
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
